---
title: Error Handling
description: Learn more about how to handle errors in CallApi
icon: ShieldAlert
---

It prevalent knowledge that making network requests is inherently risky. Things can go wrong for many reasons:

- The server might be down.
- The server might respond with an error status like 404 Not Found (the resource doesn't exist) or 500 Internal Server Error (something broke on the server).
- There might be a network issue.
- The request might time out.
- The response data might not be in the format you expected (e.g., not valid JSON).

When using the standard browser fetch API, handling these failures can sometimes be a bit clunky due to the following reasons:

- Network errors throw one type of error
- Non-2xx HTTP responses don't throw errors by default (you have to check response.ok)
- Parsing errors might throw yet another type

This can lead to complex if/else chains and unwieldy try...catch blocks just to figure out what went wrong.

CallApi aims to make dealing with these failures much more predictable and convenient.

## Structure of the `error` property

As introduced in the [Getting Started](./getting-started.mdx) guide, CallApi wraps responses in a result object with three key properties: `data`, `error`, and `response`.

When something goes wrong while making a request, the `error` property will contain a structured object detailing the problem.

The `error` property is an object that has the following properties:

1. **name**: A string identifying the type of error (e.g., `'HTTPError'`, `'ValidationError'`, `'TypeError'`, `'TimeoutError'`, ...etc).

2. **message**: A brief description of what went wrong:
   - For HTTP errors: The error message from the server, or if not provided, falls back to the `defaultErrorMessage` option
   - For validation errors: A formatted error message derived from the validation issues array
   - For non-HTTP errors: The error message from the JavaScript error object that caused the error

3. **errorData**: The detailed error information:
   - For HTTP errors: It is set to the parsed response from the API
   - For validation errors: It is set to the validation issues array
   - For non-HTTP errors: It is set to `false`

4. **originalError**: The original error object that caused the error:
   - For HTTP errors: `HTTPError`
   - For validation errors: `ValidationError`
   - For non-HTTP errors: The underlying javascript error object (e.g., `TypeError`, `DOMException`, etc.)

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";

const { error } = await callApi("https://my-api.com/api/v1/session");
// @annotate: Hover over the error object to see the type
```

## Handling HTTP Errors (HTTPError)

One of the most common types of errors you'll encounter is when the server responds with a status code outside the 200-299 range (like 400, 401, 403, 404, 500, 503, etc.). Standard `fetch` doesn't throw an error for these responses.

CallApi, by default, wraps these responses in an `HTTPError`.
You can customize the error response data type by providing a second generic type argument to callApi.

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";

type ErrorData = {
	message: string;
	errors: Array<string | string[]>;
};

const { error } = await callApi<unknown, ErrorData>("/api/endpoint");

if (error) {
	console.log(error.errorData);
}
```

Since the `error` property is a discriminated union, you can use the `isHTTPError` utility from `@zayne-labs/callapi/utils` to check if it's an HTTP error:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isHTTPError } from "@zayne-labs/callapi/utils";

type UserData = {
	id: number;
	userId: string;
	title: string;
	completed: boolean;
};

type ErrorResponseData = {
	message?: string;
	errors?: Array<string | string[]>;
};

const { data, error } = await callApi<UserData, ErrorResponseData>("https://my-api.com/api/v1/session");

if (isHTTPError(error)) {
	console.error(error);
	console.error(error.name); // 'HTTPError'
	console.error(error.message);
	console.error(error.errorData); // Will be set to the error response data
}
```

## Handling Validation Errors (ValidationError)

While covered in more detail in the [Validation](./validation.mdx) section, CallApi also has built-in support for schema validation.
If you configure a schema (whether for any request option or for the response data) and the received data does not match that schema, CallApi will wrap this failure in a `ValidationError`.

You can use the `isValidationError` utility to check specifically for this error type:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isValidationError } from "@zayne-labs/callapi/utils";
import * as z from "zod";

const dataSchema = z.object({
	id: z.number(),
	userId: z.string(),
	title: z.string(),
	completed: z.boolean(),
});

const { data, error } = await callApi("https://my-api.com/api/v1/session", {
	schema: {
		data: dataSchema,
	},
});

if (isValidationError(error)) {
	console.error(error);
	console.error(error.name); // 'ValidationError'
	console.error(error.message);
	console.error(error.errorData); // Will be set to the validation issues array
}
```

As seen in the case above, if the data received from the API does not match the schema, the `ValidationError` thrown will be captured in the `error` property.

## Handling Thrown Errors

Sometimes you might prefer that the error is thrown by CallApi instead of returned as a value in the result object. You can do this by setting the `throwOnError` option to `true`:
This is especially useful when integrating with libraries that expect promises to reject on failure, such as React Query for example.

You can use the `isHTTPErrorInstance` and `isValidationErrorInstance` utilities to check if the error is an instance of `HTTPError` or `ValidationError` respectively.

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isHTTPErrorInstance, isValidationErrorInstance } from "@zayne-labs/callapi/utils";

type UserData = {
	id: number;
	userId: string;
	title: string;
	completed: boolean;
};

type ErrorResponseData = {
	message?: string;
	errors?: Array<string | string[]>;
};

try {
	const { data } = await callApi<UserData>("https://my-api.com/api/v1/session", {
		throwOnError: true,
	});
} catch (error) {
	if (isHTTPErrorInstance<ErrorResponseData>(error)) {
		console.error(error);
		console.error(error.name);
		console.error(error.message);
		console.error(error.errorData);
	}

	if (isValidationErrorInstance(error)) {
		console.error(error);
		console.error(error.name);
		console.error(error.message);
		console.error(error.errorData);
	}
}
```

## The `data` and `error` properties as a discriminated union

Another way to look at the `data` and `error` properties is as a pair of mutually exclusive properties.

This implies that:

- If `error` is present, `data` is null.
- If `error` is null, `data` is present.

TypeScript understands this relationship. So if you check for error first and handle it, TypeScript can automatically narrow the type of `data` to exclude null.

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isHTTPError } from "@zayne-labs/callapi/utils";

type UserData = {
	id: number;
	userId: string;
	title: string;
	completed: boolean;
};

type ErrorResponseData = {
	message?: string;
	errors?: Array<string | string[]>;
};

const { data, error } = await callApi<UserData, ErrorResponseData>("https://my-api.com/api/v1/session");

if (isHTTPError(error)) {
	console.error(error);
} else if (error) {
	console.error(error);
} else {
	console.log(data); // TypeScript knows data is not null here
}
// @annotate: Hover over the data object to see the narrowed type
```
